# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-11 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('app', models.CharField(blank=True, db_column='app', max_length=32, null=True)),
                ('version', models.CharField(blank=True, db_column='version', max_length=32, null=True)),
                ('id', models.CharField(blank=True, db_column='id', max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=255, null=True)),
                ('content', models.TextField(blank=True, db_column='content', null=True)),
                ('date', models.DateField(db_column='date', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, db_column='rating', null=True)),
                ('lang', models.CharField(blank=True, db_column='lang', max_length=32, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'app',
            },
        ),
        migrations.CreateModel(
            name='Word_count',
            fields=[
                ('date_word', models.CharField(db_column='date_word', max_length=32, primary_key=True)),
                ('date', models.DateField(db_column='date', primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, db_column='word', max_length=32, null=True)),
                ('total_count', models.IntegerField(blank=True, db_column='total_count', null=True)),
                ('r1_count', models.IntegerField(blank=True, db_column='r1_count', null=True)),
                ('r2_count', models.IntegerField(blank=True, db_column='r2_count', null=True)),
                ('r3_count', models.IntegerField(blank=True, db_column='r3_count', null=True)),
                ('r4_count', models.IntegerField(blank=True, db_column='r4_count', null=True)),
                ('r5_count', models.IntegerField(blank=True, db_column='r5_count', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'app_word',
            },
        ),
    ]
