# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eng',
            fields=[
                ('app', models.CharField(blank=True, db_column='app', max_length=32, null=True)),
                ('version', models.CharField(blank=True, db_column='version', max_length=32, null=True)),
                ('id', models.CharField(blank=True, db_column='author_id', max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=255, null=True)),
                ('content', models.TextField(blank=True, db_column='content', null=True)),
                ('date', models.DateField(db_column='date', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, db_column='rating', null=True)),
                ('lang', models.CharField(blank=True, db_column='lang', max_length=32, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'app_en',
            },
        ),
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('app', models.CharField(blank=True, db_column='app', max_length=32, null=True)),
                ('version', models.CharField(blank=True, db_column='version', max_length=32, null=True)),
                ('id', models.CharField(blank=True, db_column='author_id', max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=255, null=True)),
                ('content', models.TextField(blank=True, db_column='content', null=True)),
                ('date', models.DateField(db_column='date', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, db_column='rating', null=True)),
                ('lang', models.CharField(blank=True, db_column='lang', max_length=32, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'app',
            },
        ),
    ]
