# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-09 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastleBurn',
            fields=[
                ('app', models.CharField(blank=True, db_column='app', max_length=32, null=True)),
                ('id', models.CharField(blank=True, db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('title', models.CharField(blank=True, db_column='title', max_length=255, null=True)),
                ('content', models.TextField(blank=True, db_column='content', null=True)),
                ('rating', models.IntegerField(blank=True, db_column='rating', null=True)),
                ('lang', models.CharField(blank=True, db_column='lang', max_length=32, null=True)),
            ],
            options={
                'db_table': 'castleburn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CastleBurn_count',
            fields=[
                ('date', models.DateField(db_column='date', primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, db_column='word', max_length=32, null=True)),
                ('total_count', models.IntegerField(blank=True, db_column='total_count', null=True)),
                ('r1_count', models.IntegerField(blank=True, db_column='r1_count', null=True)),
                ('r2_count', models.IntegerField(blank=True, db_column='r2_count', null=True)),
                ('r3_count', models.IntegerField(blank=True, db_column='r3_count', null=True)),
                ('r4_count', models.IntegerField(blank=True, db_column='r4_count', null=True)),
                ('r5_count', models.IntegerField(blank=True, db_column='r5_count', null=True)),
            ],
            options={
                'db_table': 'castleburn_count',
                'managed': False,
            },
        ),
    ]
